### Using OOP in Regression Analysis

In [3]:
from abc import ABC, abstractmethod
import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neural_network import MLPRegressor

class MLModel(ABC):
    @abstractmethod
    def train(self, X, y):
        pass

    @abstractmethod
    def predict(self, X):
        pass



### Linear OOP Regression

In [9]:
class LinearRegressionModel(MLModel):
    def __init__(self):
        self.model = LinearRegression()
        
    def train(self, X, y):
        self.model.fit(X, y)
        
    def predict(self, X):
        return self.model.predict(X)


### Polynomial Regression OOP Structure

In [5]:
class PolynomialRegressionModel(MLModel):
    def __init__(self, degree=2):
        self.degree = degree
        self.poly = PolynomialFeatures(degree)
        self.model = LinearRegression()
        
    def train(self, X, y):
        X_poly = self.poly.fit_transform(X)
        self.model.fit(X_poly, y)
        
    def predict(self, X):
        X_poly = self.poly.transform(X)
        return self.model.predict(X_poly)


### Logistic Regression OOP Structure

In [6]:
class LogisticRegressionModel(MLModel):
    def __init__(self):
        self.model = LogisticRegression()
        
    def train(self, X, y):
        self.model.fit(X, y)
        
    def predict(self, X):
        # Returns probability of positive class (can use threshold if needed)
        return self.model.predict_proba(X)[:, 1]


### Neural Network using OOP Structure

In [7]:
class NeuralNetworkRegressionModel(MLModel):
    def __init__(self, hidden_layer_sizes=(100,)):
        self.model = MLPRegressor(hidden_layer_sizes=hidden_layer_sizes, max_iter=1000)
        
    def train(self, X, y):
        self.model.fit(X, y)
        
    def predict(self, X):
        return self.model.predict(X)


### Synthetic Data Generation
 Randomly generating data points to analyse
 X = np.random.rand(100, 1)
 y = 3 * X.squeeze() + 2 + np.random.randn(100) * 0.1
 X: 100 random values between 0 and 1.
 y: A linear relationship with some noise added, so the true relation is roughly y = 3X + 2.
 Fit Models and Predict
Trains each model (linear regression, polynomial regression, neural network regression) on this data.
Makes predictions on the same dataset.
Output
Adding Print Statements 

print(predictions_linear[:5])
print(predictions_poly[:5])
print(predictions_nn[:5])
You'd see the first five predicted values for each model.
What do the predictions look like?
Linear regression: Predicted values close to the true y values, as the data is linear.
Polynomial regression: Also close, could capture more complex relationships if present.
Neural network regression: Predicted values similar, but may differ depending on model complexity and random initialisation.
Example Output (not exact, but illustrative):

[2.10, 2.31, 2.22, 2.44, 2.19]  # Linear model
[2.09, 2.30, 2.22, 2.40, 2.18]  # Polynomial (degree=3)
[2.12, 2.29, 2.22, 2.41, 2.21]  # Neural network
These values represent the model's predictions for the first five points in X.

Summary:
The example is meant to show you how to use the defined classes. Its output, if you add print statements or plot, will be predicted numeric values for the input data, generated by each regression model. You can extend this by evaluating performance or visualising results!







In [8]:
# Example usage (with synthetic data)
if __name__ == "__main__":
    # Create synthetic data
    X = np.random.rand(100, 1)
    y = 3 * X.squeeze() + 2 + np.random.randn(100) * 0.1

    linear_model = LinearRegressionModel()
    linear_model.train(X, y)
    predictions_linear = linear_model.predict(X)

    poly_model = PolynomialRegressionModel(degree=3)
    poly_model.train(X, y)
    predictions_poly = poly_model.predict(X)

    nn_model = NeuralNetworkRegressionModel(hidden_layer_sizes=(50, 20))
    nn_model.train(X, y)
    predictions_nn = nn_model.predict(X)

    print(predictions_linear[:5])
    print(predictions_poly[:5])
    print(predictions_nn[:5])


[2.81047859 3.48317116 3.72669471 2.06658932 2.58564382]
[2.82149853 3.5004083  3.74012186 2.02565515 2.58693853]
[2.96702256 3.52350535 3.72495943 2.37368529 2.78102871]
