Using OOP in Regression Analysis

In [6]:
from abc import ABC, abstractmethod
import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neural_network import MLPRegressor

class MLModel(ABC):
    @abstractmethod
    def train(self, X, y):
        pass

    @abstractmethod
    def predict(self, X):
        pass



In [7]:
class LinearRegressionModel(MLModel):
    def __init__(self):
        self.model = LinearRegression()
        
    def train(self, X, y):
        self.model.fit(X, y)
        
    def predict(self, X):
        return self.model.predict(X)


In [8]:
class PolynomialRegressionModel(MLModel):
    def __init__(self, degree=2):
        self.degree = degree
        self.poly = PolynomialFeatures(degree)
        self.model = LinearRegression()
        
    def train(self, X, y):
        X_poly = self.poly.fit_transform(X)
        self.model.fit(X_poly, y)
        
    def predict(self, X):
        X_poly = self.poly.transform(X)
        return self.model.predict(X_poly)


In [9]:
class LogisticRegressionModel(MLModel):
    def __init__(self):
        self.model = LogisticRegression()
        
    def train(self, X, y):
        self.model.fit(X, y)
        
    def predict(self, X):
        # Returns probability of positive class (can use threshold if needed)
        return self.model.predict_proba(X)[:, 1]


In [10]:
class NeuralNetworkRegressionModel(MLModel):
    def __init__(self, hidden_layer_sizes=(100,)):
        self.model = MLPRegressor(hidden_layer_sizes=hidden_layer_sizes, max_iter=1000)
        
    def train(self, X, y):
        self.model.fit(X, y)
        
    def predict(self, X):
        return self.model.predict(X)


In [13]:
# Example usage (with synthetic data)
if __name__ == "__main__":
    # Create synthetic data
    X = np.random.rand(100, 1)
    y = 3 * X.squeeze() + 2 + np.random.randn(100) * 0.1

    linear_model = LinearRegressionModel()
    linear_model.train(X, y)
    predictions_linear = linear_model.predict(X)

    poly_model = PolynomialRegressionModel(degree=3)
    poly_model.train(X, y)
    predictions_poly = poly_model.predict(X)

    nn_model = NeuralNetworkRegressionModel(hidden_layer_sizes=(50, 20))
    nn_model.train(X, y)
    predictions_nn = nn_model.predict(X)

    print(predictions_linear[:5])
    print(predictions_poly[:5])
    print(predictions_nn[:5])


[4.11055395 2.74098239 3.01446    2.04779723 4.64539322]
[4.0784108  2.74182514 2.99767706 2.09796469 4.66194871]
[4.07018506 2.83041667 3.07821118 2.2260387  4.54694102]
